# This file is intended for use with Admin API 2 running in multi-tenant mode,
# along with ODS/API 7.x in multi-tenant mode. It assumes there are two
# different tenants named "tenant1" and "tenant2". Each has only one ODS
# instance.

@adminapi_url=https://localhost:7214
@adminapi_client=adminapi_client
@adminapi_secret=adminapi_SECRET_2025_rftyguhijkotgyhuijok

### Register a new client
POST {{adminapi_url}}/connect/register
Content-Type: application/x-www-form-urlencoded

ClientId={{adminapi_client}}&ClientSecret={{adminapi_secret}}&DisplayName=Admin+API+{{adminapi_client}}

### Get a token
# @name tokenRequest
POST {{adminapi_url}}/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: basic {{adminapi_client}}:{{adminapi_secret}}

grant_type=client_credentials&scope=edfi_admin_api/full_access

###
@token={{tokenRequest.response.body.access_token}}


### Get ods instances
GET {{adminapi_url}}/v2/odsinstances
Content-Type: application/json
Authorization: bearer {{token}}


### Get application
GET {{adminapi_url}}/v2/applications/1
Content-Type: application/json
Authorization: bearer {{token}}


### Get all apiclients by application
GET {{adminapi_url}}/v2/apiclients?applicationid=1
Content-Type: application/json
Authorization: bearer {{token}}


### Create ApiClient
POST {{adminapi_url}}/v2/apiclients
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "ApiClient1",
  "isApproved": true,
  "applicationId": 1,
  "odsInstanceIds": [
    1
  ]
}

### Update ApiClient
PUT {{adminapi_url}}/v2/apiclients/2
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "ApiClient1 updated",
  "isApproved": true,
  "applicationId": 1,
  "odsInstanceIds": [
    1
  ]
}

### get apiclient
GET {{adminapi_url}}/v2/apiclients/2
Content-Type: application/json
Authorization: bearer {{token}}


### Reset apiclient secret
PUT {{adminapi_url}}/v2/apiclients/2/reset-credential
Content-Type: application/json
Authorization: bearer {{token}}





### Reset application secret
PUT {{adminapi_url}}/v2/applications/2/reset-credential
Content-Type: application/json
Authorization: bearer {{token}}


### delete apiclient
DELETE {{adminapi_url}}/v2/apiclients/2
Content-Type: application/json
Authorization: bearer {{token}}
