# This file is intended for use with Admin API 2 running in multi-tenant mode,
# along with ODS/API 7.x in multi-tenant mode. It assumes there are two
# different tenants named "tenant1" and "tenant2". Each has only one ODS
# instance.

@adminapi_url=https://localhost:7214
@adminapi_client=adminapi_client
@adminapi_secret=adminapi_SECRET_2025_rftyguhijkotgyhuijok

### Register a new client
POST {{adminapi_url}}/connect/register
Content-Type: application/x-www-form-urlencoded

ClientId={{adminapi_client}}&ClientSecret={{adminapi_secret}}&DisplayName=Admin+API+{{adminapi_client}}

### Get a token
# @name tokenRequest
POST {{adminapi_url}}/connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: basic {{adminapi_client}}:{{adminapi_secret}}

grant_type=client_credentials&scope=edfi_admin_api/full_access

###
@token={{tokenRequest.response.body.access_token}}

### Use the token
GET {{adminapi_url}}/v2/vendors
Authorization: bearer {{token}}

### Use an expired token
GET {{adminapi_url}}/v2/vendors
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlBLUVBDSFFYUko5UDdMU0RCSllTUlZSRkREVFFYVkFTSV9COVdXTUsiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiJhZG1pbmFwaV9jbGllbnQiLCJvaV9wcnN0IjoiYWRtaW5hcGlfY2xpZW50IiwiY2xpZW50X2lkIjoiYWRtaW5hcGlfY2xpZW50Iiwib2lfdGtuX2lkIjoiMiIsInNjb3BlIjoiZWRmaV9hZG1pbl9hcGkvZnVsbF9hY2Nlc3MiLCJqdGkiOiJhYmY4NjQ1MC05OTIwLTQyODItYmYyMy1jZmU2ZGI1MTQwN2YiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjE0LyIsImV4cCI6MTczODc5NzcwNCwiaWF0IjoxNzM4Nzk1OTA0fQ.BIkw1JjA6KqJHquZd8r_h6MOi-89cn6QvQfwr1Z1Zohnn9cCRkV3c_bDupF7abxhI1dNoKvD1zYeFzUvfdfG4rlK9aXD_XzkbvF5gZkRV6hxaZlSaT0Vp5l02ZENjsIryPTBDYFXtJIEEf0OJ9N2EIaeEf0pwBrpyeLagJAC13XiCKQWO8oM0i1YgsardPuWfhujQdn4RErIcvyWRGQNOGkpzUgU_29LpvM_I_cPLyvQLi2KOlxJAiJceTgxa9ARYoVpiUBIb9QS6XpAWTy4bhbtFuz9KAm0BzawucXvSkUKA4CmMdMkkUlXHhvFtsiYSicnFkUB6nhOZudrRqdQCg

### Use a corrupt token (bad signature)
GET {{adminapi_url}}/v2/vendors
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlBLUVBDSFFYUko5UDdMU0RCSllTUlZSRkREVFFYVkFTSV9COVdXTUsiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiJhZG1pbmFwaV9jbGllbnQiLCJvaV9wcnN0IjoiYWRtaW5hcGlfY2xpZW50IiwiY2xpZW50X2lkIjoiYWRtaW5hcGlfY2xpZW50Iiwib2lfdGtuX2lkIjoiMiIsInNjb3BlIjoiZWRmaV9hZG1pbl9hcGkvZnVsbF9hY2Nlc3MiLCJqdGkiOiJhYmY4NjQ1MC05OTIwLTQyODItYmYyMy1jZmU2ZGI1MTQwN2YiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjE0LyIsImV4cCI6MTczODc5NzcwNCwiaWF0IjoxNzM4Nzk1OTA0fQ.BIkw1JjA6KqJHquZd8r_h6MOi-89cn6QvQfwr1Z1Zohnn9cCRkV3c_bDupF7abxhI1dNoKvD1zYeFzUvfdfG4rlK9aXD_XzkbvF5gZkRV6hxaZlSaT0Vp5l02ZENjsIryPTBDYFXtJIEEf0OJ9N2EIaeEf0pwBrpyeLagJAC13XiCKQWO8oM0i1YgsardPuWfhujQdn4RErIcvyWRGQNOGkpzUgU_29LpvM_I_cPLyvQLi2KOlxJAiJceTgxa9ARYoVpiUBIb9QS6XpAWTy4bhbtFuz9KAm0BzawucXvSkUKA4CmMdMkkUlXHhvFtsiYSicnFkUB6nhOZudrRqdQcG

### Use a corrupt token (bad header)
GET {{adminapi_url}}/v2/vendors
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbmFwaV9jbGllbnQiLCJvaV9wcnN0IjoiYWRtaW5hcGlfY2xpZW50IiwiY2xpZW50X2lkIjoiYWRtaW5hcGlfY2xpZW50Iiwib2lfdGtuX2lkIjoiMiIsInNjb3BlIjoiZWRmaV9hZG1pbl9hcGkvZnVsbF9hY2Nlc3MiLCJqdGkiOiJhYmY4NjQ1MC05OTIwLTQyODItYmYyMy1jZmU2ZGI1MTQwN2YiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjE0LyIsImV4cCI6MTczODc5NzcwNCwiaWF0IjoxNzM4Nzk1OTA0fQ.BIkw1JjA6KqJHquZd8r_h6MOi-89cn6QvQfwr1Z1Zohnn9cCRkV3c_bDupF7abxhI1dNoKvD1zYeFzUvfdfG4rlK9aXD_XzkbvF5gZkRV6hxaZlSaT0Vp5l02ZENjsIryPTBDYFXtJIEEf0OJ9N2EIaeEf0pwBrpyeLagJAC13XiCKQWO8oM0i1YgsardPuWfhujQdn4RErIcvyWRGQNOGkpzUgU_29LpvM_I_cPLyvQLi2KOlxJAiJceTgxa9ARYoVpiUBIb9QS6XpAWTy4bhbtFuz9KAm0BzawucXvSkUKA4CmMdMkkUlXHhvFtsiYSicnFkUB6nhOZudrRqdQCg

