# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: "3.8"

services:
  db-ods:
    image: edfialliance/ods-api-db-ods:pre-6x
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-P@ssw0rd}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    volumes:
      - vol-db-ods-adminapi:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods-adminapi

  nginx:
    build:
      context: ../../Settings/gateway/
      dockerfile: Dockerfile
    environment:
      ADMIN_API_VIRTUAL_NAME: "${ADMIN_API_VIRTUAL_NAME:-adminapi}"
      ODS_VIRTUAL_NAME: "${ODS_VIRTUAL_NAME:-api}"
    ports:
      - "443:443"
      - "80:80"
    container_name: ed-fi-gateway-adminapi
    restart: always
    hostname: nginx
    volumes:
      - ../../Settings/ssl:/ssl/
    depends_on:
      - adminapi
      - api

  api:
    image: edfialliance/ods-api-web-api:pre-6x
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-P@55w0rd}"
      POSTGRES_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      ODS_POSTGRES_HOST: pb-ods
      ADMIN_POSTGRES_HOST: pb-admin
      API_MODE: "SharedInstance"
      ApiSettings__PathBase: "${ODS_VIRTUAL_NAME:-api}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    depends_on:
      - pb-ods
      - pb-admin
    restart: always
    hostname: webapi
    container_name: ed-fi-ods-api-adminapi

  pb-ods:
    image: pgbouncer/pgbouncer@sha256:aa8a38b7b33e5fe70c679053f97a8e55c74d52b00c195f0880845e52b50ce516 #pgbouncer:1.15.0
    environment:
      DATABASES: "* = host = db-ods port=5432 user=${POSTGRES_USER:-postgres} password=${POSTGRES_PASSWORD:-P@55w0rd}"
      PGBOUNCER_LISTEN_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
    ports:
      - "5402:${PGBOUNCER_LISTEN_PORT:-6432}"
    restart: always
    container_name: ed-fi-pb-ods-adminapi
    depends_on:
      - db-ods

  adminapi:
    build:
      # Important to set the context to the root, rather than setting it to the
      # EdFi.Ods.AdminApi directory, so that the Dockerfile has access to other
      # C# projects.
      context: ../../
      additional_contexts:
         assets: ../../../
      dockerfile: dev.mssql.Dockerfile
    environment:
      ADMIN_MSSQL_HOST: db-admin
      SQLSERVER_ADMIN_DATASOURCE: db-admin
      SQLSERVER_SECURITY_DATASOURCE: db-admin
      SQLSERVER_ODS_DATASOURCE: db-admin
      SQLSERVER_PORT: 1433
      SQLSERVER_USER: ${SQLSERVER_USER:-edfi}
      SQLSERVER_PASSWORD: "${SQLSERVER_PASSWORD:-P@55w0rd}"
      DATABASEENGINE: "SqlServer"
      API_MODE: ${API_MODE}
      AUTHORITY: ${AUTHORITY}
      ISSUER_URL: ${ISSUER_URL}
      SIGNING_KEY: ${SIGNING_KEY}
      ADMIN_API_VIRTUAL_NAME: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
      ODS_API_VERSION: ${ODS_API_VERSION}
    depends_on:
      - db-admin
    restart: always
    hostname: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
    container_name: adminapi
    healthcheck:
      test: ${ADMIN_API_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  db-admin:
    build:
      context: ../../Settings/DB-Admin/mssql/
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-P@55w0rd}"
      ACCEPT_EULA: "Y"
      SQLSERVER_ADMIN_DATASOURCE: db-admin
      SQLSERVER_ODS_DATASOURCE: db-admin
      SQLSERVER_PORT: 1433
      SQLSERVER_USER: ${SQLSERVER_USER:-edfi}
      SQLSERVER_PASSWORD: "${SQLSERVER_PASSWORD:-P@55w0rd}"
    ports:
      - 1433:1433
    volumes:
      - vol-db-admin-adminapi:/var/lib/mssql/data
    restart: always
    container_name: ed-fi-db-admin-adminapi

  pb-admin:
    image: pgbouncer/pgbouncer@sha256:aa8a38b7b33e5fe70c679053f97a8e55c74d52b00c195f0880845e52b50ce516 #pgbouncer:1.15.0
    environment:
      DATABASES: "* = host = db-admin port=5432 user=${POSTGRES_USER:-postgres} password=${POSTGRES_PASSWORD:-P@55w0rd}"
      PGBOUNCER_LISTEN_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
    ports:
      - "5401:${PGBOUNCER_LISTEN_PORT:-6432}"
    restart: always
    container_name: ed-fi-pb-admin-adminapi
    depends_on:
      - pb-ods

volumes:
  vol-db-admin-adminapi:
    driver: local
    name: vol-db-admin-adminapi
  vol-db-ods-adminapi:
    driver: local
    name: vol-db-ods-adminapi
