openapi: 3.0.1
info:
  title: Admin API Documentation
  description: 'The Ed-Fi Admin API is a REST API-based administrative interface for managing vendors, applications, client credentials, and authorization rules for accessing an Ed-Fi API.'
  version: adminconsole
paths:
  /:
    get:
      tags:
        - Information
      summary: Retrieve API informational metadata
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/informationResult'
        '500':
          description: Internal server error. An unhandled error occurred on the server. See the response body for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/informationResult'
  /connect/register:
    post:
      tags:
        - Connect
      summary: Registers new client
      description: Registers new client
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ClientId:
                  type: string
                  description: Client id
                ClientSecret:
                  type: string
                  description: Client secret
                DisplayName:
                  type: string
                  description: Client display name
            encoding:
              ClientId:
                style: form
              ClientSecret:
                style: form
              DisplayName:
                style: form
      responses:
        '400':
          description: Bad Request. The request was invalid and cannot be completed. See the response body for details.
        '500':
          description: Internal server error. An unhandled error occurred on the server. See the response body for details.
        '200':
          description: Application registered successfully.
  /connect/token:
    post:
      tags:
        - Connect
      summary: Retrieves bearer token
      description: "\nTo authenticate Swagger requests, execute using \"Authorize\" above, not \"Try It Out\" here."
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: 'string '
                client_secret:
                  type: 'string '
                grant_type:
                  type: 'string '
                scope:
                  type: string
      responses:
        '400':
          description: 'Bad request, such as invalid scope.'
        '500':
          description: Internal server error. An unhandled error occurred on the server. See the response body for details.
        '200':
          description: Sign-in successful.
components:
  schemas:
    adminApiError:
      title: AdminApiError
      type: object
      additionalProperties: false
      description: Wrapper schema for all error responses
    informationResult:
      title: Information
      type: object
      properties:
        version:
          type: string
          description: Application version
        build:
          type: string
          description: Build / release version
      additionalProperties: false
    registerClientRequest:
      title: RegisterClientRequest
      type: object
      properties:
        clientId:
          type: string
          description: Client id
        clientSecret:
          type: string
          description: Client secret
        displayName:
          type: string
          description: Client display name
      additionalProperties: false
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://localhost/connect/token
          scopes:
            edfi_admin_api/full_access: Full access to the Admin API
            edfi_admin_api/tenant_access: Access to a specific tenant
            edfi_admin_api/worker: Worker access to the Admin API
security:
  - oauth:
      - api